### CREATE a document
POST http://localhost:5000/plantrip HTTP/1.1
content-type: application/json

{
    "destination": "Denver",
    "startDate": "2023-01-25",
    "endDate": "2023-01-29"
}

### CREATE another document
POST http://localhost:5000/plantrip HTTP/1.1
content-type: application/json

{
    "destination": "Seattle",
    "startDate": "2023-02-14",
    "endDate": "2023-02-28"
}

### RETRIEVE all documents
GET http://localhost:5000/plantrip HTTP/1.1

### RETRIEVE a document by its ID
GET http://localhost:5000/plantrip/665cb15f02b3d49a46e46cae HTTP/1.1


### UPDATE a document by its ID
PUT http://localhost:5000/plantrip/665cb15f02b3d49a46e46cae HTTP/1.1
content-type: application/json

{
    "destination": "Orlando",
    "startDate": "2023-03-10",
    "endDate": "2023-03-14"
}


### DELETE a document by its ID
DELETE http://localhost:5000/plantrip/665cb13c02b3d49a46e46cab HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:5000/plantrip HTTP/1.1
